name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: python.exe -m pip install --upgrade pip
    - run: pip install openpyxl pandas spacy xlsxwriter PySide6 nuitka
    - run: python -m spacy download en_core_web_sm
    - run: |
        nuitka --onefile --windows-disable-console --name=SentimentApp --enable-plugin=pyside6 --include-data-file=mainwindow.ui=. --include-data-file=backend_functions.py=. main_app.py --show-progress --verbose
        Get-ChildItem SentimentApp.exe
        if (Test-Path SentimentApp.exe) { Write-Output "EXE FOUND"; Get-ChildItem} else { Write-Output "NO EXE" }
    - uses: actions/upload-artifact@v4
      with:
        name: SentimentApp-exe
        path: SentimentApp.exe
