name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Upgrade pip
      run: python.exe -m pip install --upgrade pip
    - name: Install stable Numpy version
      run: pip install "numpy==1.26.4"
    - name: Check if Numpy works before Nuitka
      run: python -c "import numpy; print(f'\nNumpy {numpy.__version__} works.')"
    - name: Install stable dependencies
      run: pip install openpyxl pandas spacy xlsxwriter PySide6 zstandard nuitka
    - name: Check Pandas for Numpy errors
      run: python -c "import pandas; print(f'\nPandas {pandas.__version__} works.')"
    - name: Download the neural network and copy it into the repository
      run: |
        python -m spacy download en_core_web_sm
        python -c "
        import os, shutil, spacy
        model_path = spacy.util.get_package_path('en_core_web_sm')
        shutil.copytree(model_path, './en_core_web_sm', dirs_exist_ok = True)
        print('\nModel copied into ./en_core_web_sm')"
        dir en_core_web_sm\\config.cfg
    - name: Unzip DLLs
      run: Expand-Archive dlls_minimal.zip -DestinationPath .
      
    - name: Build
      run: |
        nuitka --onefile --windows-console-mode=disable --output-filename=SentimentApp-v1.0.0 --enable-plugin=pyside6 --include-package=numpy --include-package=numpy.core --include-package-data=numpy --include-data-dir=dlls_minimal=. --include-data-dir=en_core_web_sm=en_core_web_sm --include-data-file=mainwindow.ui=mainwindow.ui --include-data-file=backend_functions.py=backend_functions.py main_app.py --assume-yes-for-downloads --show-progress --verbose
        Get-ChildItem SentimentApp-v1.0.0.exe
        if (Test-Path SentimentApp-v1.0.0.exe) { Write-Output "EXE FOUND"; Get-ChildItem} else { Write-Output "NO EXE" }
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: SentimentApp-v1.0.0
        path: SentimentApp-v1.0.0.exe
